[package]
name = "question1"
version = "0.1.0"
authors = ["AbrarFastian <abrarkhan_1998@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
